# Generated by Django 6.0.3 on 2026-03-20 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(default='PENDIENTE', max_length=20)),
            ],
            options={
                'db_table': 'pedido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad_empaque', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id_tienda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_sucursal', models.CharField(max_length=10, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tienda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cant_sugerida', models.IntegerField()),
                ('cant_ajustada', models.IntegerField(blank=True, null=True)),
                ('cant_recibida', models.IntegerField(blank=True, null=True)),
                ('pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='nucleo.pedido')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='nucleo.producto')),
            ],
            options={
                'db_table': 'detalle_pedido',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='tienda',
            field=models.ForeignKey(db_column='id_tienda', on_delete=django.db.models.deletion.PROTECT, to='nucleo.tienda'),
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_lote', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='nucleo.producto')),
                ('tienda', models.ForeignKey(db_column='id_tienda', on_delete=django.db.models.deletion.CASCADE, to='nucleo.tienda')),
            ],
            options={
                'db_table': 'lote',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InventarioProducto',
            fields=[
                ('id_inv_prod', models.AutoField(primary_key=True, serialize=False)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_min', models.IntegerField()),
                ('stock_max', models.IntegerField()),
                ('ventas_prom_dia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='nucleo.producto')),
                ('tienda', models.ForeignKey(db_column='id_tienda', on_delete=django.db.models.deletion.CASCADE, to='nucleo.tienda')),
            ],
            options={
                'db_table': 'inventario_producto',
                'managed': True,
                'unique_together': {('tienda', 'producto')},
            },
        ),
    ]
