# Generated by Django 6.0.3 on 2026-07-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='barra',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
