# Generated by Django 6.0.3 on 2026-07-12 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('nucleo', '0002_producto_barra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rol', models.CharField(max_length=20)),
                ('tienda', models.ForeignKey(db_column='id_tienda', on_delete=django.db.models.deletion.CASCADE, to='nucleo.tienda')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
