# Generated by Django 6.0.3 on 2026-07-30 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioproducto',
            name='producto',
            field=models.ForeignKey(db_column='sku', on_delete=django.db.models.deletion.CASCADE, to='nucleo.producto'),
        ),
    ]
