# Generated by Django 6.0.3 on 2026-07-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_alter_inventarioproducto_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarioproducto',
            name='stock_max',
        ),
        migrations.RemoveField(
            model_name='inventarioproducto',
            name='stock_min',
        ),
        migrations.RemoveField(
            model_name='inventarioproducto',
            name='ventas_prom_dia',
        ),
    ]
