# Generated by Django 6.0.3 on 2026-09-08 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_remove_lote_cantidad_pedido_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('numero_factura', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('cantidad_vendida', models.IntegerField()),
                ('precio_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_producto', models.ForeignKey(db_column='sku', on_delete=django.db.models.deletion.PROTECT, to='nucleo.producto', to_field='sku')),
                ('tienda', models.ForeignKey(db_column='id_tienda', on_delete=django.db.models.deletion.PROTECT, to='nucleo.tienda')),
            ],
        ),
    ]
