# Generated by Django 6.0.3 on 2026-09-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0007_ventas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='numero_factura',
            field=models.CharField(max_length=100),
        ),
    ]
