# Generated by Django 6.0.3 on 2026-09-14 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0008_alter_ventas_numero_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisReposicion',
            fields=[
                ('inventario', models.OneToOneField(db_column='id_inv_prod', help_text='Producto en tienda al que pertenece este análisis.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='analisis_reposicion', serialize=False, to='nucleo.inventarioproducto')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última vez que se recalculó este análisis.')),
                ('periodo_desde', models.DateField(help_text='Inicio de la ventana de ventas analizada.')),
                ('periodo_hasta', models.DateField(help_text='Fin de la ventana de ventas analizada.')),
                ('dias_analizados', models.PositiveIntegerField(help_text='Cantidad de días usados para el promedio.')),
                ('promedio_venta_diario', models.DecimalField(decimal_places=3, help_text='Demanda diaria promedio (DDP).', max_digits=10)),
                ('stock_seguridad', models.DecimalField(decimal_places=2, help_text='Colchón ante variabilidad: DDP × días de seguridad.', max_digits=10)),
                ('reorder_point', models.DecimalField(decimal_places=2, help_text='ROP: DDP × lead time + stock de seguridad.', max_digits=10)),
                ('stock_maximo', models.DecimalField(decimal_places=2, help_text='Objetivo tras reponer: ROP + DDP × ciclo de reposición.', max_digits=10)),
                ('leadtime', models.PositiveIntegerField(help_text='Lead time (en días) usado en este cálculo.')),
                ('dias_seguridad_usados', models.PositiveIntegerField(help_text='Días de stock de seguridad usados en este cálculo.')),
                ('ciclo_usado', models.PositiveIntegerField(help_text='Días de ciclo de reposición usados en este cálculo.')),
            ],
            options={
                'verbose_name': 'Análisis de reposición',
                'verbose_name_plural': 'Análisis de reposición',
                'db_table': 'analisis_reposicion',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='ciclo_reposicion_dias',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='producto',
            name='dias_stock_seguridad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='producto',
            name='lead_time_dias',
            field=models.IntegerField(default=1),
        ),
    ]
