# Generated by Django 6.0.3 on 2026-09-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0009_analisisreposicion_producto_ciclo_reposicion_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='dias_historial_ventas',
            field=models.IntegerField(default=30),
        ),
    ]
