# Generated by Django 6.0.3 on 2026-09-26 00:58

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0010_producto_dias_historial_ventas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventarioproducto',
            options={'base_manager_name': 'todos', 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='lote',
            options={'base_manager_name': 'todos', 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'base_manager_name': 'todos', 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ventas',
            options={'base_manager_name': 'todos'},
        ),
        migrations.AlterModelManagers(
            name='inventarioproducto',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='lote',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='pedido',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='ventas',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['tienda', 'codigo_producto', 'fecha'], name='nucleo_vent_id_tien_f52ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['fecha'], name='nucleo_vent_fecha_893471_idx'),
        ),
    ]
