# Generated by Django 6.1.1 on 2026-10-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0011_alter_inventarioproducto_options_alter_lote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_recepcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estatus',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('CA', 'Cancelado'), ('AP', 'Aprobado'), ('RE', 'Recibido')], default='PE', max_length=20),
        ),
    ]
