# Generated by Django 6.1.1 on 2026-10-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0012_pedido_fecha_aprobacion_pedido_fecha_recepcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estatus',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('CA', 'Cancelado'), ('AP', 'Aprobado'), ('RE', 'Recibido')], default='PE', max_length=20),
        ),
    ]
