# Generated by Django 6.1.1 on 2026-10-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0013_alter_pedido_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cuadrante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
