# Generated by Django 6.1.1 on 2026-10-07 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0014_producto_cuadrante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'base_manager_name': 'todos', 'managed': True, 'ordering': ['fecha_vencimiento']},
        ),
        migrations.AddField(
            model_name='lote',
            name='cantidad',
            field=models.IntegerField(default=0, help_text='Unidades en este lote.'),
        ),
        migrations.AddField(
            model_name='lote',
            name='detalle_origen',
            field=models.ForeignKey(blank=True, db_column='id_detalle_origen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_generados', to='nucleo.detallepedido'),
        ),
        migrations.AddField(
            model_name='lote',
            name='pedido_origen',
            field=models.ForeignKey(blank=True, db_column='id_pedido_origen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_generados', to='nucleo.pedido'),
        ),
    ]
