"""
Django settings for configuraciones project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jwcar(z6f8dd#89c-zx47$p79^02l#s6wmufwg543po@q&kwu)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "nucleo",
    "debug_toolbar",
    "accounts.apps.AccountsConfig"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = 'configuraciones.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/ "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'configuraciones.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    #'default': {
        #'ENGINE': 'django.db.backends.postgresql',
        #'NAME': 'granjademo',
        #'USER': 'postgres',
       # 'PASSWORD': '27725361',
      #  'HOST': '127.0.0.1',
     #   'PORT': '5432',
    #}
      'default': {#esto es para correr las pruebas en sqlite
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS= [BASE_DIR, "static"]
INTERNAL_IPS = [
    "127.0.0.1",
]

LOGIN_REDIRECT_URL= "home"
LOGOUT_REDIRECT_URL = "/login/"

JAZZMIN_SETTINGS = {
    # Título de la ventana del navegador
    "site_title": "Granja Mercados Admin",

    # Encabezado en la pantalla de Login y barra superior
    "site_header": "Granja Mercados",

    # Subtítulo/Marca en la barra superior
    "site_brand": "Granja Mercados",

    # Mensaje de bienvenida en la pantalla de login
    "welcome_sign": "Bienvenido al Sistema de Gestión e Inventario",

    # Derechos de autor en el pie de página
    "copyright": "Granja Mercados C.A.",

    
    
    # Logo de la empresa (debe estar en tu carpeta static, ej: static/img/logo.png)
     "site_logo": "static/img/photo.jpg",
     "custom_css": "css/admin_custom.css",

    # Menú lateral colapsable estilo Dashboard profesional
    "show_sidebar": True,
    "navigation_expanded": True,

    # Iconos para tus modelos en el menú lateral (Usa FontAwesome 5/6)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        # Ejemplo para tus apps propias:
        "nucleo.Tienda": "fas fa-store",
        "nucleo.Producto": "fas fa-boxes",
        "nucleo.Pedido": "fas fa-truck-loading",
    },
    "custom_links": {
        "auth": [{
            "name": "Cerrar Sesión", 
            "url": "admin:logout", 
            "icon": "fas fa-sign-out-alt",
            "permissions": ["auth.view_user"]
        }],
    },
    
   
}

JAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-primary navbar-dark",       # Barra superior azul
    "theme": "flatly",                             # Tema limpio de Bootstrap
    "sidebar": "sidebar-dark-primary",            # Menú lateral oscuro con acentos azules
    "accent": "accent-primary",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}